---
6/10/2020
Chapter5-3
---
if「某個條件符合才執行」
```{r}
if(condition){Body for TRUE} #condition:它是個「是/否」問句(使用條件判斷來產生答案T/F，是個logical)
```
1.
```{r}
# 先執行此行輸入學號
readline(prompt = "請輸入你的學號") -> studentId 
```
```{r}
# 之後才執行以下程式
library(stringr)
if(str_detect(studentId,'^[43](1[01][0-9]|9[0-9])[0-9]{5}$',negate=T)){warning("你所輸入的學號不正確")}
```
4|119|73003
 | ~ |
3| 99|
```{r}
if(!require(lubridate)){install.packages("lubridate")} #condition:是否"沒安裝lubridate"
lubridate::ymd_hms("2020-07-01 13:00:00 GMT")
```
require:使否有安裝該程式(回應為T/F)
2.
```{r}
convert_TaiwanDate2WesternDate <- function(twDate){
  library(stringr)
  regex_pattern <- "(?<=民國)[0-9]+(?=年)" #取出民國年，計算西元年
  
  year <- str_extract(twDate,regex_pattern)
  westernYear <- as.integer(year)+1911 #替換民國xx年的xx成西元年數字
  
  str_replace(
    twDate,
    regex_pattern,  #要換掉的文字
    as.character(westernYear) #要換上的內容
  ) -> twDate_reformat
  
  lubridate::ymd(twDate_reformat) -> westernDate
  return(westernDate)
}

twDate <-  c("民國108年12月5日","民國98年10月5日")
convert_TaiwanDate2WesternDate(twDate)
```
```{r}
convert_TaiwanDate2WesternDate <- function(twDate){
  
  if(!require("stringr")){install.packages("stringr")}
  if(!require("lubridate")){install.packages("lubridate")}
  
  library(stringr)regex_pattern <- "(?<=民國)[0-9]+(?=年)"
  
  # 取出民國年，計算西元年
  year <- str_extract(twDate,regex_pattern)
  westernYear <- as.integer(year)+1911
  
  # 替換民國xx年的xx成西元年數字
  str_replace(
    twDate,
    regex_pattern,  # 要換掉的文字
    as.character(westernYear) # 要替換的內容
  ) -> twDate_reformat
  
  lubridate::ymd(twDate_reformat) -> westernDate
  return(westernDate)
}
```
3.不重覆下載
```{r}
system.time(jsonlite::fromJSON("https://opendata.cwb.gov.tw/fileapi/v1/opendataapi/F-C0032-001?Authorization=rdec-key-123-45678-011121314&format=JSON")
  -> weather_next36hours) #檢視步驟耗時elapse time
```
```{r}
if(!exists("weather_next36hours")){
    jsonlite::fromJSON("https://opendata.cwb.gov.tw/fileapi/v1/opendataapi/F-C0032-001?Authorization=rdec-key-123-45678-011121314&format=JSON") ->
    weather_next36hours #只記在腦海中
  SOAR::Store(weather_next36hours) #存在.R_cache environment中
}
```
範例:
```{r}
askSilly_weather <- function(locationInput,dateInput){
  jsonlite::fromJSON("https://opendata.cwb.gov.tw/fileapi/v1/opendataapi/F-C0032-001?Authorization=rdec-key-123-45678-011121314&format=JSON") ->
  weather_next36hours
  
  (weather_next36hours$cwbopendata$dataset$location$locationName == locationInput) -> pick_location
  
  weather_next36hours$cwbopendata$dataset$location$weatherElement[pick_location][[1]] -> weatherAtLocation
  (weatherAtLocation$elementName=="MaxT") ->  pick_MaxT
  (weatherAtLocation$elementName=="MinT") -> pick_MinT
  weatherAtLocation$time[pick_MaxT][[1]]$parameter$parameterName[[1]] -> maxT
  weatherAtLocation$time[pick_MinT][[1]]$parameter$parameterName[[1]] -> minT
  
  glue::glue("{locationInput} {dateInput} 氣溫，最高{maxT}度，最低{minT}度。")
}
```
askSilly_weather2會暫存，跑更快
```{r}
askSilly_weather2 <- function(locationInput,dateInput){
  if(!exists("weather_next36hours")){
      jsonlite::fromJSON("https://opendata.cwb.gov.tw/fileapi/v1/opendataapi/F-C0032-001?Authorization=rdec-key-123-45678-011121314&format=JSON") ->
      weather_next36hours
    SOAR::Store(weather_next36hours) # 存在.R_cache environment中
  }  
  (weather_next36hours$cwbopendata$dataset$location$locationName == locationInput) -> pick_location
  
  weather_next36hours$cwbopendata$dataset$location$weatherElement[pick_location][[1]] -> weatherAtLocation
  (weatherAtLocation$elementName=="MaxT") ->pick_MaxT
  (weatherAtLocation$elementName=="MinT") ->pick_MinT
  weatherAtLocation$time[pick_MaxT][[1]]$parameter$parameterName[[1]] -> maxT
  weatherAtLocation$time[pick_MinT][[1]]$parameter$parameterName[[1]] -> minT
  
  glue::glue("{locationInput} {dateInput} 氣溫，最高{maxT}度，最低{minT}度。")
}
```
4.if else
```{r}
if(condition){ body for TRUE condition} else {body for FALSE condition}
```
f(n) = n/2      if n is even
     = -(n+1)/2 if n is odd
```{r}
n <- 54
if(as.logical(n %% 2)){fvalue <- -(n+1)/2} else {fvalue <- n/2}
```
```{r}
myFun <- function(n){
  if(as.logical(n %% 2)){fvalue <- -(n+1)/2} else {fvalue <- n/2}
  return(fvalue)
}
myFun(54)
myFun(33)
```
5. 提早交卷時間
```{r}
jsonlite::fromJSON("https://www.dropbox.com/s/d14j5hp3i5ps657/examSubmissionTimes.json?dl=1") -> examSubmissionTime
head(examSubmissionTime$section)
head(examSubmissionTime$time)
```
有兩個交卷時間: 56節 or 78節
一位同學提早時間：
```{r}
i<-1
student_i_section <- examSubmissionTime$section[[i]]
student_i_time <- examSubmissionTime$time[[i]]

if(student_i_section=="56"){
  deadline <- lubridate::ymd_hms("2020-05-27 15:00:00", tz="Asia/Taipei")
} else {deadline <- lubridate::ymd_hms("2020-05-27 17:00:00", tz="Asia/Taipei")}

howEarly <- deadline - lubridate::ymd_hms(student_i_time, tz="Asia/Taipei")
print(howEarly)
```
每位同學提早時間：
```{r}
compute_howEarly <- function(student_i_section, student_i_time){
  if(student_i_section=="56"){
    deadline <- lubridate::ymd_hms("2020-05-27 15:00:00", tz="Asia/Taipei")
  } else {
    deadline <- lubridate::ymd_hms("2020-05-27 17:00:00", tz="Asia/Taipei")
  }
  
  howEarly <- deadline - lubridate::ymd_hms(student_i_time, tz="Asia/Taipei")
  return(howEarly)
}
```
```{r}
studentSequence <- 1:length(examSubmissionTime$section)
library(purrr)
map(studentSequence,
    ~compute_howEarly(examSubmissionTime$section[[.x]],examSubmissionTime$time[[.x]])
    ) -> list_howEarly
```
78節和56節交卷提早時間比較
```{r}
library(magrittr)
list_howEarly %>%
  unlist() -> examSubmissionTime$howEarly

pick_56 <- examSubmissionTime$section=="56"
mean(examSubmissionTime$howEarly[pick_56])
median(examSubmissionTime$howEarly[pick_56])

pick_78 <- examSubmissionTime$section=="78"
mean(examSubmissionTime$howEarly[pick_78])
median(examSubmissionTime$howEarly[pick_78])
```
6.if…else if… else
```{r}
if(condition A){
  body for A 
} else if(condition B){
  body for B
} else if(condition C){
  body for C
} else {
  body for none of the above
}
```
7.成績等級
```{r}
readline("請輸入你的成績（整數):") -> grade # 單獨執行
```
```{r}
if(grade >=90){
  print("優")
} else if(grade>=80 & grade<=89){
  print("良")
} else if(grade>=70 & grade<=79){
  print("尚可")
} else {
  print("待加強")
}
```
#各情境一定要互斥，即不可以有兩個情境有可能同時為TRUE，如果發生多個情境吻合會以第一個結果的body來執行。
