---
---

```{r setup, include=FALSE}
# 10位學生的主系
majors10_char <- c('經濟學系','社會學系','社會學系','經濟學系','經濟學系','社會學系','經濟學系','經濟學系','經濟學系','社會學系')

typeof(majors10_char)
class(majors10_char)
```

```{r cars}
majors10_factor <- factor(majors10_char)
# 或
majors10_factor <- factor(
  c('經濟學系','社會學系','社會學系','經濟學系','經濟學系','社會學系','經濟學系','經濟學系','經濟學系','社會學系')
)

typeof(majors10_factor)
class(majors10_factor)
```

```{r pressure, echo=FALSE}
library(lubridate)
tpeTime <- ymd_hms("2020-03-18 13:52:40",
        tz="Asia/Taipei")
```

```{r}
tpeTime <- c("2020-03-18 13:52:40",
             "2020-03-11 03:12:40")
tpeTime <- 
  ymd_hms(
    tpeTime, # 呼叫tpeTime向量值
    tz="Asia/Taipei"
    )
```

```{r}
browseURL("https://docs.google.com/spreadsheets/d/1EAG49qDKPWWi0ebkVr29TLrvVnoBPfkvxYY-J3xLAHY/edit#gid=458686645")
```

```{r}
stdentTime <- c(
  ymd_hms("2020-03-11T06:56:17Z"),
  ymd_hms("2020-03-11 03:12:40",tz="Asia/Taipei"),
  ymd_hms("2020-03-11 13:52:40",tz="Asia/Taipei"))

```

